# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2022-01-09 00:13+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 3.0\n"
"X-Poedit-Basepath: ..\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: tests\n"

#: _error.py:13
msgid "The file lock '{}' could not be acquired. Is another instance of pleroma-bot running?"
msgstr ""

#: _pin.py:28
msgid "Pinning post:\t{}"
msgstr ""

#: _pin.py:62
msgid "Unpinning previous:\t{}"
msgstr ""

#: _pin.py:66
msgid "File with previous pinned post ID not found or empty. Checking last posts for pinned post..."
msgstr ""

#: _pin.py:71
msgid "Pinned post not found. Giving up unpinning..."
msgstr ""

#: _pleroma.py:43
msgid "No posts were found in the target Fediverse account"
msgstr ""

#: _pleroma.py:107
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media size too large:\n"
"Filename: {file}\n"
"Size: {size}MB\n"
"Consider increasing the attachment\n"
" size limit of your instance"
msgstr ""

#: _pleroma.py:122
msgid "Error uploading media:\t{}"
msgstr ""

#: _pleroma.py:155
msgid "Post in Pleroma:\t{}"
msgstr ""

#: _pleroma.py:219
msgid ""
"Total number of metadata fields cannot exceed 4.\n"
"Provided: {}. Exiting..."
msgstr ""

#: _pleroma.py:257
msgid ""
"Exception occurred\n"
"Error code 422\n"
"(Unprocessable Entity)\n"
"Please check that the bio text or the metadata fields text\n"
"aren't too long."
msgstr ""

#: _pleroma.py:267
msgid "Updating profile:\t {}"
msgstr ""

#: _processing.py:199
#, python-brace-format
msgid ""
"Exception occurred\n"
"Media not found (404)\n"
"{tweet} - {media_url}\n"
"Ignoring attachment and continuing..."
msgstr ""

#: _processing.py:224
msgid "Attachment exceeded config file size limit ({})"
msgstr ""

#: _processing.py:228
msgid "File size: {}MB"
msgstr ""

#: _processing.py:232
msgid "Ignoring attachment and continuing..."
msgstr ""

#: _processing.py:315
msgid "Couldn't expand the {}: {}"
msgstr ""

#: _twitter.py:130
msgid "API version not supported: {}"
msgstr ""

#: _twitter.py:146
msgid "max_tweets must be between 10 and 3200. max_tweets: {}"
msgstr ""

#: _twitter.py:296
msgid "Gathering tweets... "
msgstr ""

#: _utils.py:142
msgid "Processing tweets... "
msgstr ""

#: _utils.py:205
msgid "Attempting to acquire lock {} on {}"
msgstr ""

#: _utils.py:212
msgid "Lock {} acquired on {}"
msgstr ""

#: _utils.py:218
msgid "Timeout on acquiring lock {} on {}"
msgstr ""

#: _utils.py:224
msgid "Lock {} not acquired on {}, waiting {} seconds ..."
msgstr ""

#: _utils.py:259
msgid "Attempting to release lock {} on {}"
msgstr ""

#: _utils.py:264
msgid "Lock {} released on {}"
msgstr ""

#: _utils.py:316
msgid "Current pinned:\t{}"
msgstr ""

#: _utils.py:327
msgid "Previous pinned:\t{}"
msgstr ""

#: _utils.py:454
msgid "Instance response was not understood {}"
msgstr ""

#: _utils.py:459
msgid "Assuming target instance is Mastodon..."
msgstr ""

#: _utils.py:464
msgid "Mastodon doesn't support display names longer than 30 characters, truncating it and trying again..."
msgstr ""

#: _utils.py:472
msgid "Mastodon doesn't support rich text. Disabling it..."
msgstr ""

#: _utils.py:478
msgid "How far back should we retrieve tweets from the Twitter account?"
msgstr ""

#: _utils.py:481
msgid ""
"\n"
"Enter a date (YYYY-MM-DD):\n"
"[Leave it empty to retrieve *ALL* tweets or enter 'continue'\n"
"if you want the bot to execute as normal (checking date of \n"
"last post in the Fediverse account)] "
msgstr ""

#: _utils.py:497 _utils.py:504
msgid "Raising max_tweets to the maximum allowed value"
msgstr ""

#: cli.py:146
msgid "No Pleroma URL defined in config! [pleroma_base_url]"
msgstr ""

#: cli.py:150
msgid "Visibility not supported! Values allowed are: {}"
msgstr ""

#: cli.py:180
msgid "Some or all OAuth 1.0a tokens missing, falling back to application-only authentication"
msgstr ""

#: cli.py:220
msgid "Bot for mirroring one or multiple Twitter accounts in Pleroma/Mastodon."
msgstr ""

#: cli.py:233
msgid "path of config file (config.yml) to use and parse. If not specified, it will try to find it in the current working directory."
msgstr ""

#: cli.py:247
msgid "path of log file (error.log) to create. If not specified, it will try to store it at your config file path"
msgstr ""

#: cli.py:260
msgid "skips Fediverse profile update (no background image, profile image, bio text, etc.)"
msgstr ""

#: cli.py:274
msgid "forces the tweet retrieval to start from a specific date. The twitter_username value (FORCEDATE) can be supplied to only force it for that particular user in the config"
msgstr ""

#: cli.py:287
msgid "skips first run checks"
msgstr ""

#: cli.py:297
msgid "path of the Twitter archive file (zip) to use for posting tweets."
msgstr ""

#: cli.py:323
msgid "Debug logging enabled"
msgstr ""

#: cli.py:333
msgid "config path: {}"
msgstr ""

#: cli.py:334
msgid "tweets temp folder: {}"
msgstr ""

#: cli.py:348
msgid "Multiple twitter users for one Fediverse account, skipping profile and pinned tweet."
msgstr ""

#: cli.py:358
msgid "Processing user:\t{}"
msgstr ""

#: cli.py:368
msgid "It seems like pleroma-bot is running for the first time for this Twitter user: {}"
msgstr ""

#: cli.py:427
msgid ""
"Unable to retrieve tweets. Is the account protected? If so, you need to provide the following OAuth 1.0a fields in the user config:\n"
" - consumer_key \n"
" - consumer_secret \n"
" - access_token_key \n"
" - access_token_secret"
msgstr ""

#: cli.py:436
msgid "tweets gathered: \t {}"
msgstr ""

#: cli.py:444
msgid "tweets to post: \t {}"
msgstr ""

#: cli.py:468
msgid "Multiple twitter users, not updating profile"
msgstr ""

#: cli.py:475
msgid "Exception occurred"
msgstr ""
